name: Build Fabric Mod

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          cache-read-only: false
          
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Fix build.gradle (if needed)
        run: |
          if [ -f "build.gradle.kts" ]; then
            echo "Using Kotlin DSL build script"
            # 修复Kotlin DSL版本的build.gradle.kts
            sed -i 's/fabric-loom" version "1.[0-9]\+\.[0-9]\+"/fabric-loom" version "1.0.17"/g' build.gradle.kts
            sed -i 's/minecraft("com.mojang:minecraft:1.21.[0-9]\+")/minecraft("com.mojang:minecraft:1.20.4")/g' build.gradle.kts
          else
            echo "Using Groovy build script"
            # 修复Groovy版本的build.gradle
            sed -i "s/id 'fabric-loom' version '[0-9]\+\.[0-9]\+\.[0-9]\+'/id 'fabric-loom' version '1.0.17'/g" build.gradle
            sed -i "s/minecraft 'com.mojang:minecraft:1.21.[0-9]\+'/minecraft 'com.mojang:minecraft:1.20.4'/g" build.gradle
          fi

      - name: Setup Fabric repositories
        run: |
          mkdir -p ~/.gradle
          echo "systemProp.gradle.internal.network.validateCertificates=false" >> ~/.gradle/gradle.properties
          echo "org.gradle.caching=true" >> ~/.gradle/gradle.properties
          echo "org.gradle.parallel=true" >> ~/.gradle/gradle.properties
          echo "org.gradle.jvmargs=-Xmx2G" >> ~/.gradle/gradle.properties
          echo "fabric.loom.multiProjectOptimisation=true" >> ~/.gradle/gradle.properties

      - name: Update settings.gradle file
        run: |
          if [ -f "settings.gradle.kts" ]; then
            cat > settings.gradle.kts << 'EOL'
            pluginManagement {
                repositories {
                    gradlePluginPortal()
                    maven("https://maven.fabricmc.net/")
                    maven("https://maven.quiltmc.org/repository/release")
                    maven("https://maven.minecraftforge.net/")
                }
                plugins {
                    id("fabric-loom") version "1.0.17"
                }
            }
            rootProject.name = "iseeyou"
            EOL
          else
            cat > settings.gradle << 'EOL'
            pluginManagement {
                repositories {
                    gradlePluginPortal()
                    maven { url "https://maven.fabricmc.net/" }
                    maven { url "https://maven.quiltmc.org/repository/release" }
                    maven { url "https://maven.minecraftforge.net/" }
                }
                plugins {
                    id "fabric-loom" version "1.0.17"
                }
            }
            rootProject.name = "iseeyou"
            EOL
          fi

      - name: Build with Gradle
        run: ./gradlew build
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ISeeYou-Fabric-Mod
          path: build/libs/*.jar
          
      - name: Generate build report
        if: always()
        run: ./gradlew --buildScan

      - name: Create release (on tag)
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 