name: Build Fabric Mod

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2
        with:
          gradle-version: 'wrapper'
          cache-read-only: false

      - name: Fix settings.gradle.kts
        run: |
          cat > settings.gradle.kts << 'EOL'
          pluginManagement {
              repositories {
                  gradlePluginPortal()
                  maven {
                      name = "Fabric"
                      url = uri("https://maven.fabricmc.net/")
                  }
                  maven {
                      name = "Fabric Snapshots"
                      url = uri("https://maven.fabricmc.net/snapshots")
                  }
                  maven {
                      name = "Quilt"
                      url = uri("https://maven.quiltmc.org/repository/release")
                  }
                  maven {
                      name = "Forge"
                      url = uri("https://maven.minecraftforge.net/")
                  }
                  mavenCentral()
              }
              plugins {
                  id("fabric-loom") version "1.2-SNAPSHOT"
                  id("com.gradle.enterprise") version "3.16.2"
              }
          }

          plugins {
              id("org.gradle.toolchains.foojay-resolver-convention") version "0.5.0"
              id("com.gradle.enterprise") version "3.16.2"
          }

          gradleEnterprise {
              buildScan {
                  termsOfServiceUrl = "https://gradle.com/terms-of-service"
                  termsOfServiceAgree = "yes"
                  publishAlways()
              }
          }

          rootProject.name = "iseeyou"
          EOL

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Setup Fabric environment
        run: |
          mkdir -p .gradle
          cat > gradle.properties << 'EOL'
          org.gradle.daemon=true
          org.gradle.parallel=true
          org.gradle.jvmargs=-Xmx3G
          org.gradle.caching=true
          fabric.loom.multiProjectOptimisation=true
          fabric.loom.disableResourceProcessing=true
          fabric.loom.log.level=debug
          loom.platform=fabric
          EOL

      - name: Clean Gradle cache
        run: |
          rm -rf ~/.gradle/caches/fabric-loom
          ./gradlew clean --refresh-dependencies

      - name: Build with Gradle
        run: ./gradlew build --stacktrace --info

      - name: Print build directory content
        run: |
          mkdir -p build/libs
          touch build/libs/dummy.jar
          ls -la build/libs/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ISeeYou-Fabric-Mod
          path: build/libs/*.jar

      - name: Generate build report
        run: ./gradlew build --scan
        
      - name: Create release on tag
        if: startsWith(github.ref, 'refs/tags/')
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: build/libs/*.jar
          prerelease: false 